#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fribidi
Version  : 0.19.7
Release  : 3
URL      : http://fribidi.org/download/fribidi-0.19.7.tar.bz2
Source0  : http://fribidi.org/download/fribidi-0.19.7.tar.bz2
Summary  : Unicode Bidirectional Algorithm Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: fribidi-bin
Requires: fribidi-lib
Requires: fribidi-doc
BuildRequires : glib-dev

%description
This is GNU FriBidi
The Free Implementation of the Unicode Bidirectional Algorithm.

%package bin
Summary: bin components for the fribidi package.
Group: Binaries

%description bin
bin components for the fribidi package.


%package dev
Summary: dev components for the fribidi package.
Group: Development
Requires: fribidi-lib
Requires: fribidi-bin
Provides: fribidi-devel

%description dev
dev components for the fribidi package.


%package doc
Summary: doc components for the fribidi package.
Group: Documentation

%description doc
doc components for the fribidi package.


%package lib
Summary: lib components for the fribidi package.
Group: Libraries

%description lib
lib components for the fribidi package.


%prep
%setup -q -n fribidi-0.19.7

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483109244
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fribidi

%files dev
%defattr(-,root,root,-)
/usr/include/fribidi/fribidi-arabic.h
/usr/include/fribidi/fribidi-begindecls.h
/usr/include/fribidi/fribidi-bidi-types-list.h
/usr/include/fribidi/fribidi-bidi-types.h
/usr/include/fribidi/fribidi-bidi.h
/usr/include/fribidi/fribidi-char-sets-list.h
/usr/include/fribidi/fribidi-char-sets.h
/usr/include/fribidi/fribidi-common.h
/usr/include/fribidi/fribidi-config.h
/usr/include/fribidi/fribidi-deprecated.h
/usr/include/fribidi/fribidi-enddecls.h
/usr/include/fribidi/fribidi-flags.h
/usr/include/fribidi/fribidi-joining-types-list.h
/usr/include/fribidi/fribidi-joining-types.h
/usr/include/fribidi/fribidi-joining.h
/usr/include/fribidi/fribidi-mirroring.h
/usr/include/fribidi/fribidi-shape.h
/usr/include/fribidi/fribidi-types.h
/usr/include/fribidi/fribidi-unicode-version.h
/usr/include/fribidi/fribidi-unicode.h
/usr/include/fribidi/fribidi.h
/usr/lib64/libfribidi.so
/usr/lib64/pkgconfig/fribidi.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfribidi.so.0
/usr/lib64/libfribidi.so.0.3.6
