#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fribidi
Version  : 1.0.10
Release  : 16
URL      : https://github.com/fribidi/fribidi/releases/download/v1.0.10/fribidi-1.0.10.tar.xz
Source0  : https://github.com/fribidi/fribidi/releases/download/v1.0.10/fribidi-1.0.10.tar.xz
Summary  : Unicode Bidirectional Algorithm Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: fribidi-bin = %{version}-%{release}
Requires: fribidi-lib = %{version}-%{release}
Requires: fribidi-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config

%description


%package bin
Summary: bin components for the fribidi package.
Group: Binaries
Requires: fribidi-license = %{version}-%{release}

%description bin
bin components for the fribidi package.


%package dev
Summary: dev components for the fribidi package.
Group: Development
Requires: fribidi-lib = %{version}-%{release}
Requires: fribidi-bin = %{version}-%{release}
Provides: fribidi-devel = %{version}-%{release}
Requires: fribidi = %{version}-%{release}

%description dev
dev components for the fribidi package.


%package dev32
Summary: dev32 components for the fribidi package.
Group: Default
Requires: fribidi-lib32 = %{version}-%{release}
Requires: fribidi-bin = %{version}-%{release}
Requires: fribidi-dev = %{version}-%{release}

%description dev32
dev32 components for the fribidi package.


%package lib
Summary: lib components for the fribidi package.
Group: Libraries
Requires: fribidi-license = %{version}-%{release}

%description lib
lib components for the fribidi package.


%package lib32
Summary: lib32 components for the fribidi package.
Group: Default
Requires: fribidi-license = %{version}-%{release}

%description lib32
lib32 components for the fribidi package.


%package license
Summary: license components for the fribidi package.
Group: Default

%description license
license components for the fribidi package.


%prep
%setup -q -n fribidi-1.0.10
cd %{_builddir}/fribidi-1.0.10
pushd ..
cp -a fribidi-1.0.10 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595347463
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1595347463
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fribidi
cp %{_builddir}/fribidi-1.0.10/COPYING %{buildroot}/usr/share/package-licenses/fribidi/597bf5f9c0904bd6c48ac3a3527685818d11246d
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fribidi

%files dev
%defattr(-,root,root,-)
/usr/include/fribidi/fribidi-arabic.h
/usr/include/fribidi/fribidi-begindecls.h
/usr/include/fribidi/fribidi-bidi-types-list.h
/usr/include/fribidi/fribidi-bidi-types.h
/usr/include/fribidi/fribidi-bidi.h
/usr/include/fribidi/fribidi-brackets.h
/usr/include/fribidi/fribidi-char-sets-list.h
/usr/include/fribidi/fribidi-char-sets.h
/usr/include/fribidi/fribidi-common.h
/usr/include/fribidi/fribidi-config.h
/usr/include/fribidi/fribidi-deprecated.h
/usr/include/fribidi/fribidi-enddecls.h
/usr/include/fribidi/fribidi-flags.h
/usr/include/fribidi/fribidi-joining-types-list.h
/usr/include/fribidi/fribidi-joining-types.h
/usr/include/fribidi/fribidi-joining.h
/usr/include/fribidi/fribidi-mirroring.h
/usr/include/fribidi/fribidi-shape.h
/usr/include/fribidi/fribidi-types.h
/usr/include/fribidi/fribidi-unicode-version.h
/usr/include/fribidi/fribidi-unicode.h
/usr/include/fribidi/fribidi.h
/usr/lib64/libfribidi.so
/usr/lib64/pkgconfig/fribidi.pc
/usr/share/man/man3/fribidi_charset_to_unicode.3
/usr/share/man/man3/fribidi_debug_status.3
/usr/share/man/man3/fribidi_get_bidi_type.3
/usr/share/man/man3/fribidi_get_bidi_type_name.3
/usr/share/man/man3/fribidi_get_bidi_types.3
/usr/share/man/man3/fribidi_get_bracket.3
/usr/share/man/man3/fribidi_get_bracket_types.3
/usr/share/man/man3/fribidi_get_joining_type.3
/usr/share/man/man3/fribidi_get_joining_type_name.3
/usr/share/man/man3/fribidi_get_joining_types.3
/usr/share/man/man3/fribidi_get_mirror_char.3
/usr/share/man/man3/fribidi_get_par_direction.3
/usr/share/man/man3/fribidi_get_par_embedding_levels.3
/usr/share/man/man3/fribidi_get_par_embedding_levels_ex.3
/usr/share/man/man3/fribidi_get_type.3
/usr/share/man/man3/fribidi_get_type_internal.3
/usr/share/man/man3/fribidi_join_arabic.3
/usr/share/man/man3/fribidi_log2vis.3
/usr/share/man/man3/fribidi_log2vis_get_embedding_levels.3
/usr/share/man/man3/fribidi_mirroring_status.3
/usr/share/man/man3/fribidi_parse_charset.3
/usr/share/man/man3/fribidi_remove_bidi_marks.3
/usr/share/man/man3/fribidi_reorder_line.3
/usr/share/man/man3/fribidi_reorder_nsm_status.3
/usr/share/man/man3/fribidi_set_debug.3
/usr/share/man/man3/fribidi_set_mirroring.3
/usr/share/man/man3/fribidi_set_reorder_nsm.3
/usr/share/man/man3/fribidi_shape.3
/usr/share/man/man3/fribidi_shape_arabic.3
/usr/share/man/man3/fribidi_shape_mirroring.3
/usr/share/man/man3/fribidi_unicode_to_charset.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libfribidi.so
/usr/lib32/pkgconfig/32fribidi.pc
/usr/lib32/pkgconfig/fribidi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfribidi.so.0
/usr/lib64/libfribidi.so.0.4.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libfribidi.so.0
/usr/lib32/libfribidi.so.0.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fribidi/597bf5f9c0904bd6c48ac3a3527685818d11246d
